language: cpp
matrix:
    include:
        # note that gcc Debug MUST be 1st for Coverity
        - os: linux
          compiler: gcc
          env: CONFIGURATION="Debug"
        - os: linux
          compiler: clang
          env: CONFIGURATION="Debug"
        - os: osx
          compiler: clang
          env: CONFIGURATION="Debug" MACOSX_ARCH=i386
        - os: osx
          compiler: clang
          env: CONFIGURATION="Debug" MACOSX_ARCH=x86_64

        - os: linux
          compiler: gcc
          env: CONFIGURATION="Release"
        - os: linux
          compiler: clang
          env: CONFIGURATION="Release"
        - os: osx
          compiler: clang
          env: CONFIGURATION="Release" MACOSX_ARCH=i386
        - os: osx
          compiler: clang
          env: CONFIGURATION="Release" MACOSX_ARCH=x86_64
before_install:
    # Exit build if it's not a release tag
    - export TEST_TAG=release_42
    - echo "$TEST_TAG"
    - RELEASE_BUILD=false
    - if [[ "$TEST_TAG" =~ ^release.* ]]; then echo "This is a release tag!" ; RELEASE_BUILD=true ; fi
    - if ([[ "$RELEASE_BUILD" == true ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "clang" ]]); then echo "Skipping non-release compiler" ; exit 0 ; fi
    - if ([[ "$RELEASE_BUILD" == true ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$MACOSX_ARCH" == "i386" ]]); then echo "Skipping non-release architecture" ; exit 0 ; fi
    - if ([[ "$RELEASE_BUILD" == true ]] && [[ "$CONFIGURATION" == "Debug" ]]); then echo "Skipping non-release configuration" ; exit 0 ; fi
script:
    - if [ "$RELEASE_BUILD" = true ] ; then echo "Releasing!"; else echo "Doing CI"; fi
