language: cpp
matrix:
    include:
        # note that gcc Debug MUST be 1st for Coverity
        - os: linux
          compiler: gcc
          env: CONFIGURATION="Debug"
        - os: linux
          compiler: clang
          env: CONFIGURATION="Debug"
        - os: osx
          compiler: clang
          env: CONFIGURATION="Debug" MACOSX_ARCH=i386
        - os: osx
          compiler: clang
          env: CONFIGURATION="Debug" MACOSX_ARCH=x86_64

        - os: linux
          compiler: gcc
          env: CONFIGURATION="Release"
        - os: linux
          compiler: clang
          env: CONFIGURATION="Release"
        - os: osx
          compiler: clang
          env: CONFIGURATION="Release" MACOSX_ARCH=i386
        - os: osx
          compiler: clang
          env: CONFIGURATION="Release" MACOSX_ARCH=x86_64
before_install:
    # Exit build if it's not a release tag
    - echo "$TRAVIS_TAG"
    - if ([[ ! "$TRAVIS_TAG" =~ "^release.*" ]]); then echo "Skipping non-release tag" ; exit 0 ; fi
    - if ([[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "clang" ]]); then echo "Skipping non-release configuration" ; exit 0 ; fi
    - echo "Releasing!!"
install:
before_script:
script:
